services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $dm: '@doctrine_mongodb.odm.document_manager'

    App\:
        resource: '../src/'
        exclude: '../src/DependencyInjection/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Add the annotation reader service
    annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader

    # Other service configurations...
